import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { auth, db } from "../firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import Login from "../components/Login";
import Widgets from "../components/Widgets";

export default function Home({ posts }) {
  const [user] = useAuthState(auth);

  return (
    <div className="home">
      <Head>
        <title>Linkedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {!user ? (
        <Login />
      ) : (
        <main className="home__body">
          <Sidebar />
          <Feed posts={posts} />
          <Widgets />
        </main>
      )}
    </div>
  );
}

export async function getServerSideProps(context) {
  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));

  return {
    props: { posts: docs },
  };
}
